#!/usr/bin/env bash
# bootstrap-ec2.sh — EC2 user-data for LLMOps in a Box
#
# Runs once on first boot as root on Amazon Linux 2023 (x86_64).
# Installs Docker + yq, clones the repo, pulls Phase 1 credentials from
# SSM Parameter Store, writes .env, and starts the Phase 1 compose stack.
#
# Prerequisites (provisioned by Terraform):
#   - IAM instance profile with ssm:GetParametersByPath on /sais/phase-1/*
#   - Credentials uploaded to SSM via: ./scripts/stack.sh secrets push
#
# Log: /var/log/bootstrap-ec2.log
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
exec > >(tee /var/log/bootstrap-ec2.log) 2>&1

# This runs headless, so the log is the only place a failed boot can be
# diagnosed from. Every error path has to say what actually broke.
die() { echo "ERROR: $*" >&2; exit 1; }

REPO_URL="https://github.com/litkhai/llmops-in-a-box.git"
REPO_DIR="/opt/llmops-in-a-box"
SSM_PATH_PREFIX="/sais/phase-1"

# Preinstalled on the standard AL2023 AMI but absent from al2023-ami-minimal.
# Fail here rather than three minutes later, mid-`dnf`.
command -v aws >/dev/null 2>&1 \
  || die "the aws CLI is not installed — this script expects the standard AL2023 AMI"

# IMDSv2 (the instance sets http_tokens = "required"). Retried: IMDS sometimes
# is not answering yet this early in boot, and an empty region would otherwise
# surface later as an unexplained SSM failure.
IMDS="http://169.254.169.254"
IMDS_CURL=(curl -fsS --retry 5 --retry-connrefused --max-time 5)

TOKEN="$("${IMDS_CURL[@]}" -X PUT "$IMDS/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || true)"
[ -n "$TOKEN" ] || die "could not obtain an IMDSv2 token from $IMDS"

REGION="$("${IMDS_CURL[@]}" -H "X-aws-ec2-metadata-token: $TOKEN" \
  "$IMDS/latest/meta-data/placement/region" || true)"
[ -n "$REGION" ] || die "could not resolve the region from IMDS"

echo "==> bootstrap-ec2.sh starting at $(date -u)"
echo "    region=$REGION  repo=$REPO_URL"

# ── 1. System packages ────────────────────────────────────────────────────────
echo "==> Installing system packages"
dnf update -y --quiet
dnf install -y docker git

# mikefarah/yq v4 — the project requires this specific fork
YQ_VERSION="v4.44.3"
curl -fsSL \
  "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" \
  -o /usr/local/bin/yq
chmod +x /usr/local/bin/yq
echo "    yq $(yq --version)"

# ── 2. Docker ─────────────────────────────────────────────────────────────────
echo "==> Configuring Docker"
systemctl enable --now docker
usermod -aG docker ec2-user

# Docker Compose v2 plugin
COMPOSE_VERSION="v2.27.1"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL \
  "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
echo "    compose $(docker compose version --short)"

# ── 3. Clone repository ───────────────────────────────────────────────────────
# Reuse an existing checkout so the script stays re-runnable by hand: reading
# the log and re-running it is the normal way to debug a failed boot.
if [ -d "$REPO_DIR/.git" ]; then
  echo "==> $REPO_DIR already present — reusing it"
else
  echo "==> Cloning $REPO_URL"
  git clone "$REPO_URL" "$REPO_DIR"
fi
chown -R ec2-user:ec2-user "$REPO_DIR"

# ── 4. Pull credentials from SSM ─────────────────────────────────────────────
echo "==> Pulling credentials from SSM  path=$SSM_PATH_PREFIX"
ENV_FILE="$REPO_DIR/.env"

# Fetch every parameter under the prefix in one call. `--recursive` so a nested
# layout does not silently return nothing; note the key below keeps only the
# last path component, so leaf names have to stay unique across groups.
# Output: tab-separated NAME<TAB>VALUE lines, one per parameter.
#
# stderr is deliberately not discarded. A missing IAM grant and an empty
# parameter store are different failures and need different fixes.
if ! PARAMS="$(aws ssm get-parameters-by-path \
  --region "$REGION" \
  --path   "$SSM_PATH_PREFIX" \
  --recursive \
  --with-decryption \
  --query  'Parameters[*].[Name,Value]' \
  --output text)"; then
  die "the SSM GetParametersByPath call failed  region=$REGION path=$SSM_PATH_PREFIX
       The AWS CLI error is logged directly above. The usual cause is an
       instance profile without ssm:GetParametersByPath on ${SSM_PATH_PREFIX}/*"
fi

if [ -z "$PARAMS" ]; then
  die "the SSM call succeeded but returned no parameters under $SSM_PATH_PREFIX
       Push credentials first:  ./scripts/stack.sh secrets push --target aws-ec2"
fi

{
  printf '# Generated by bootstrap-ec2.sh from SSM %s at %s\n' \
    "$SSM_PATH_PREFIX" "$(date -u)"
  while IFS=$'\t' read -r name value; do
    key="${name##*/}"   # strip path prefix, keep last component
    printf '%s=%s\n' "$key" "$value"
  done <<< "$PARAMS"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
chown ec2-user:ec2-user "$ENV_FILE"
echo "    wrote $ENV_FILE  ($(grep -c = "$ENV_FILE") entries)"

# ── 5. Bring the stack up ─────────────────────────────────────────────────────
echo "==> Starting Phase 1 stack"
cd "$REPO_DIR"

# Run as ec2-user: docker socket is accessible, HOME is set correctly
sudo -u ec2-user bash -lc \
  'cd /opt/llmops-in-a-box && ./scripts/stack.sh up --target docker --profile phase-1'

echo "==> bootstrap-ec2.sh complete at $(date -u)"
cat <<'EOF'
    Every service publishes on 127.0.0.1 only, so nothing is reachable from
    the internet by design. To check health from your machine, forward the
    Phase 1 ports over SSH — <public-ip> is the `public_ip` terraform output:

      ssh -N -L 3000:localhost:3000 -L 4000:localhost:4000 \
             -L 3080:localhost:3080 -L 8123:localhost:8123 \
             -L 9002:localhost:9002 ec2-user@<public-ip>

    then, with that tunnel open:

      ./scripts/stack.sh status --target docker
EOF
