#!/usr/bin/env bash
# bootstrap-ec2.sh — EC2 user-data for LLMOps in a Box
#
# Runs once on first boot as root on Amazon Linux 2023 (x86_64).
# Installs Docker + yq, clones the repo, pulls Phase 1 credentials from
# SSM Parameter Store, writes .env, and starts the Phase 1 compose stack.
#
# Prerequisites (provisioned by Terraform):
#   - IAM instance profile with ssm:GetParametersByPath on /sais/phase-1/*
#   - Credentials uploaded to SSM via: ./scripts/stack.sh secrets push
#
# Log: /var/log/bootstrap-ec2.log
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
exec > >(tee /var/log/bootstrap-ec2.log) 2>&1

REPO_URL="https://github.com/litkhai/llmops-in-a-box.git"
REPO_DIR="/opt/llmops-in-a-box"
SSM_PATH_PREFIX="/sais/phase-1"

# IMDSv2 token (required — instance uses http_tokens = "required")
TOKEN="$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")"
REGION="$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  "http://169.254.169.254/latest/meta-data/placement/region")"

echo "==> bootstrap-ec2.sh starting at $(date -u)"
echo "    region=$REGION  repo=$REPO_URL"

# ── 1. System packages ────────────────────────────────────────────────────────
echo "==> Installing system packages"
dnf update -y --quiet
dnf install -y docker git

# mikefarah/yq v4 — the project requires this specific fork
YQ_VERSION="v4.44.3"
curl -fsSL \
  "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" \
  -o /usr/local/bin/yq
chmod +x /usr/local/bin/yq
echo "    yq $(yq --version)"

# ── 2. Docker ─────────────────────────────────────────────────────────────────
echo "==> Configuring Docker"
systemctl enable --now docker
usermod -aG docker ec2-user

# Docker Compose v2 plugin
COMPOSE_VERSION="v2.27.1"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL \
  "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
echo "    compose $(docker compose version --short)"

# ── 3. Clone repository ───────────────────────────────────────────────────────
echo "==> Cloning $REPO_URL"
git clone "$REPO_URL" "$REPO_DIR"
chown -R ec2-user:ec2-user "$REPO_DIR"

# ── 4. Pull credentials from SSM ─────────────────────────────────────────────
echo "==> Pulling credentials from SSM  path=$SSM_PATH_PREFIX"
ENV_FILE="$REPO_DIR/.env"

# Fetch all parameters under the prefix in one API call.
# Output: tab-separated NAME<TAB>VALUE lines, one per parameter.
PARAMS="$(aws ssm get-parameters-by-path \
  --region "$REGION" \
  --path   "$SSM_PATH_PREFIX" \
  --with-decryption \
  --query  'Parameters[*].[Name,Value]' \
  --output text 2>/dev/null || true)"

if [ -z "$PARAMS" ]; then
  echo "ERROR: no SSM parameters found under $SSM_PATH_PREFIX"
  echo "       Push credentials first:  ./scripts/stack.sh secrets push --target aws-ec2"
  exit 1
fi

{
  printf '# Generated by bootstrap-ec2.sh from SSM %s at %s\n' \
    "$SSM_PATH_PREFIX" "$(date -u)"
  while IFS=$'\t' read -r name value; do
    key="${name##*/}"   # strip path prefix, keep last component
    printf '%s=%s\n' "$key" "$value"
  done <<< "$PARAMS"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
chown ec2-user:ec2-user "$ENV_FILE"
echo "    wrote $ENV_FILE  ($(grep -c = "$ENV_FILE") entries)"

# ── 5. Bring the stack up ─────────────────────────────────────────────────────
echo "==> Starting Phase 1 stack"
cd "$REPO_DIR"

# Run as ec2-user: docker socket is accessible, HOME is set correctly
sudo -u ec2-user bash -lc \
  'cd /opt/llmops-in-a-box && ./scripts/stack.sh up --target docker --profile phase-1'

echo "==> bootstrap-ec2.sh complete at $(date -u)"
echo "    Verify from your machine:  ./scripts/stack.sh status --target aws-ec2"
